export type FtsCountry = {
  alpha2: string
  name: string // Russian display name (first letter upper, rest lower); use .toUpperCase() for XML/API
}

// EAEU first, then alphabetical by alpha2
export const FTS_COUNTRIES: FtsCountry[] = [
  { alpha2: "RU", name: "Россия" },
  { alpha2: "BY", name: "Беларусь" },
  { alpha2: "KZ", name: "Казахстан" },
  { alpha2: "AM", name: "Армения" },
  { alpha2: "KG", name: "Кыргызстан" },
  { alpha2: "AB", name: "Абхазия" },
  { alpha2: "AD", name: "Андорра" },
  { alpha2: "AE", name: "Объединенные арабские эмираты" },
  { alpha2: "AF", name: "Афганистан" },
  { alpha2: "AG", name: "Антигуа и барбуда" },
  { alpha2: "AI", name: "Ангилья" },
  { alpha2: "AL", name: "Албания" },
  { alpha2: "AO", name: "Ангола" },
  { alpha2: "AQ", name: "Антарктида" },
  { alpha2: "AR", name: "Аргентина" },
  { alpha2: "AS", name: "Американское самоа" },
  { alpha2: "AT", name: "Австрия" },
  { alpha2: "AU", name: "Австралия" },
  { alpha2: "AW", name: "Аруба" },
  { alpha2: "AX", name: "Аландские острова" },
  { alpha2: "AZ", name: "Азербайджан" },
  { alpha2: "BA", name: "Босния и герцеговина" },
  { alpha2: "BB", name: "Барбадос" },
  { alpha2: "BD", name: "Бангладеш" },
  { alpha2: "BE", name: "Бельгия" },
  { alpha2: "BF", name: "Буркина-фасо" },
  { alpha2: "BG", name: "Болгария" },
  { alpha2: "BH", name: "Бахрейн" },
  { alpha2: "BI", name: "Бурунди" },
  { alpha2: "BJ", name: "Бенин" },
  { alpha2: "BL", name: "Сен-бартелеми" },
  { alpha2: "BM", name: "Бермуды" },
  { alpha2: "BN", name: "Бруней-даруссалам" },
  { alpha2: "BO", name: "Боливия (многонациональное государство)" },
  { alpha2: "BQ", name: "Бонэйр, синт-эстатиус и саба" },
  { alpha2: "BR", name: "Бразилия" },
  { alpha2: "BS", name: "Багамы" },
  { alpha2: "BT", name: "Бутан" },
  { alpha2: "BV", name: "Остров буве" },
  { alpha2: "BW", name: "Ботсвана" },
  { alpha2: "BZ", name: "Белиз" },
  { alpha2: "CA", name: "Канада" },
  { alpha2: "CC", name: "Кокосовые (килинг) острова" },
  { alpha2: "CD", name: "Конго, демократическая республика" },
  { alpha2: "CF", name: "Центрально-африканская республика" },
  { alpha2: "CG", name: "Конго" },
  { alpha2: "CH", name: "Швейцария" },
  { alpha2: "CI", name: "Кот д'ивуар" },
  { alpha2: "CK", name: "Острова кука" },
  { alpha2: "CL", name: "Чили" },
  { alpha2: "CM", name: "Камерун" },
  { alpha2: "CN", name: "Китай" },
  { alpha2: "CO", name: "Колумбия" },
  { alpha2: "CR", name: "Коста-рика" },
  { alpha2: "CU", name: "Куба" },
  { alpha2: "CV", name: "Кабо-верде" },
  { alpha2: "CW", name: "Кюрасао" },
  { alpha2: "CX", name: "Остров рождества" },
  { alpha2: "CY", name: "Кипр" },
  { alpha2: "CZ", name: "Чехия" },
  { alpha2: "DE", name: "Германия" },
  { alpha2: "DJ", name: "Джибути" },
  { alpha2: "DK", name: "Дания" },
  { alpha2: "DM", name: "Доминика" },
  { alpha2: "DO", name: "Доминиканская республика" },
  { alpha2: "DZ", name: "Алжир" },
  { alpha2: "EC", name: "Эквадор" },
  { alpha2: "EE", name: "Эстония" },
  { alpha2: "EG", name: "Египет" },
  { alpha2: "EH", name: "Западная сахара" },
  { alpha2: "ER", name: "Эритрея" },
  { alpha2: "ES", name: "Испания" },
  { alpha2: "ET", name: "Эфиопия" },
  { alpha2: "EU", name: "Страны евросоюза" },
  { alpha2: "FI", name: "Финляндия" },
  { alpha2: "FJ", name: "Фиджи" },
  { alpha2: "FK", name: "Фолклендские острова (мальвинские)" },
  { alpha2: "FM", name: "Микронезия (федеративные штаты)" },
  { alpha2: "FO", name: "Фарерские острова" },
  { alpha2: "FR", name: "Франция" },
  { alpha2: "GA", name: "Габон" },
  { alpha2: "GB", name: "Соединенное королевство" },
  { alpha2: "GD", name: "Гренада" },
  { alpha2: "GE", name: "Грузия" },
  { alpha2: "GF", name: "Французская гвиана" },
  { alpha2: "GG", name: "Гернси" },
  { alpha2: "GH", name: "Гана" },
  { alpha2: "GI", name: "Гибралтар" },
  { alpha2: "GL", name: "Гренландия" },
  { alpha2: "GM", name: "Гамбия" },
  { alpha2: "GN", name: "Гвинея" },
  { alpha2: "GP", name: "Гваделупа" },
  { alpha2: "GQ", name: "Экваториальная гвинея" },
  { alpha2: "GR", name: "Греция" },
  { alpha2: "GS", name: "Южн.джорджия и южн.сандвич.острова" },
  { alpha2: "GT", name: "Гватемала" },
  { alpha2: "GU", name: "Гуам" },
  { alpha2: "GW", name: "Гвинея-бисау" },
  { alpha2: "GY", name: "Гайана" },
  { alpha2: "HK", name: "Гонконг" },
  { alpha2: "HM", name: "Остров херд и острова макдональд" },
  { alpha2: "HN", name: "Гондурас" },
  { alpha2: "HR", name: "Хорватия" },
  { alpha2: "HT", name: "Гаити" },
  { alpha2: "HU", name: "Венгрия" },
  { alpha2: "ID", name: "Индонезия" },
  { alpha2: "IE", name: "Ирландия" },
  { alpha2: "IL", name: "Израиль" },
  { alpha2: "IM", name: "Остров мэн" },
  { alpha2: "IN", name: "Индия" },
  { alpha2: "IO", name: "Британская территория в индийском океане" },
  { alpha2: "IQ", name: "Ирак" },
  { alpha2: "IR", name: "Иран (исламская республика)" },
  { alpha2: "IS", name: "Исландия" },
  { alpha2: "IT", name: "Италия" },
  { alpha2: "JE", name: "Джерси" },
  { alpha2: "JM", name: "Ямайка" },
  { alpha2: "JO", name: "Иордания" },
  { alpha2: "JP", name: "Япония" },
  { alpha2: "KE", name: "Кения" },
  { alpha2: "KH", name: "Камбоджа" },
  { alpha2: "KI", name: "Кирибати" },
  { alpha2: "KM", name: "Коморы" },
  { alpha2: "KN", name: "Сент-китс и невис" },
  { alpha2: "KP", name: "Корея (народно-демократич. республика)" },
  { alpha2: "KR", name: "Корея, республика" },
  { alpha2: "KW", name: "Кувейт" },
  { alpha2: "KY", name: "Острова кайман" },
  { alpha2: "LA", name: "Лаосская народно-демократич. республика" },
  { alpha2: "LB", name: "Ливан" },
  { alpha2: "LC", name: "Сент-люсия" },
  { alpha2: "LI", name: "Лихтенштейн" },
  { alpha2: "LK", name: "Шри-ланка" },
  { alpha2: "LR", name: "Либерия" },
  { alpha2: "LS", name: "Лесото" },
  { alpha2: "LT", name: "Литва" },
  { alpha2: "LU", name: "Люксембург" },
  { alpha2: "LV", name: "Латвия" },
  { alpha2: "LY", name: "Ливия" },
  { alpha2: "MA", name: "Марокко" },
  { alpha2: "MC", name: "Монако" },
  { alpha2: "MD", name: "Молдова, республика" },
  { alpha2: "ME", name: "Черногория" },
  { alpha2: "MF", name: "Сен-мартен (французская часть)" },
  { alpha2: "MG", name: "Мадагаскар" },
  { alpha2: "MH", name: "Маршалловы острова" },
  { alpha2: "MK", name: "Северная македония" },
  { alpha2: "ML", name: "Мали" },
  { alpha2: "MM", name: "Мьянма" },
  { alpha2: "MN", name: "Монголия" },
  { alpha2: "MO", name: "Макао" },
  { alpha2: "MP", name: "Северные марианские острова" },
  { alpha2: "MQ", name: "Мартиника" },
  { alpha2: "MR", name: "Мавритания" },
  { alpha2: "MS", name: "Монтсеррат" },
  { alpha2: "MT", name: "Мальта" },
  { alpha2: "MU", name: "Маврикий" },
  { alpha2: "MV", name: "Мальдивы" },
  { alpha2: "MW", name: "Малави" },
  { alpha2: "MX", name: "Мексика" },
  { alpha2: "MY", name: "Малайзия" },
  { alpha2: "MZ", name: "Мозамбик" },
  { alpha2: "NA", name: "Намибия" },
  { alpha2: "NC", name: "Новая каледония" },
  { alpha2: "NE", name: "Нигер" },
  { alpha2: "NF", name: "Остров норфолк" },
  { alpha2: "NG", name: "Нигерия" },
  { alpha2: "NI", name: "Никарагуа" },
  { alpha2: "NL", name: "Нидерланды, королевство" },
  { alpha2: "NO", name: "Норвегия" },
  { alpha2: "NP", name: "Непал" },
  { alpha2: "NR", name: "Науру" },
  { alpha2: "NU", name: "Ниуэ" },
  { alpha2: "NZ", name: "Новая зеландия" },
  { alpha2: "OM", name: "Оман" },
  { alpha2: "OS", name: "Южная осетия" },
  { alpha2: "PA", name: "Панама" },
  { alpha2: "PE", name: "Перу" },
  { alpha2: "PF", name: "Французская полинезия" },
  { alpha2: "PG", name: "Папуа новая гвинея" },
  { alpha2: "PH", name: "Филиппины" },
  { alpha2: "PK", name: "Пакистан" },
  { alpha2: "PL", name: "Польша" },
  { alpha2: "PM", name: "Сент-пьер и микелон" },
  { alpha2: "PN", name: "Питкерн" },
  { alpha2: "PR", name: "Пуэрто-рико" },
  { alpha2: "PS", name: "Палестина, государство" },
  { alpha2: "PT", name: "Португалия" },
  { alpha2: "PW", name: "Палау" },
  { alpha2: "PY", name: "Парагвай" },
  { alpha2: "QA", name: "Катар" },
  { alpha2: "RE", name: "Реюньон" },
  { alpha2: "RO", name: "Румыния" },
  { alpha2: "RS", name: "Сербия" },
  { alpha2: "RW", name: "Руанда" },
  { alpha2: "SA", name: "Саудовская аравия" },
  { alpha2: "SB", name: "Соломоновы острова" },
  { alpha2: "SC", name: "Сейшелы" },
  { alpha2: "SD", name: "Судан" },
  { alpha2: "SE", name: "Швеция" },
  { alpha2: "SG", name: "Сингапур" },
  { alpha2: "SH", name: "Св.елена,о.вознес.,тристан-да-кунья" },
  { alpha2: "SI", name: "Словения" },
  { alpha2: "SJ", name: "Шпицберген и ян майен" },
  { alpha2: "SK", name: "Словакия" },
  { alpha2: "SL", name: "Сьерра-леоне" },
  { alpha2: "SM", name: "Сан-марино" },
  { alpha2: "SN", name: "Сенегал" },
  { alpha2: "SO", name: "Сомали" },
  { alpha2: "SR", name: "Суринам" },
  { alpha2: "SS", name: "Южный судан" },
  { alpha2: "ST", name: "Сан-томе и принсипи" },
  { alpha2: "SV", name: "Эль-сальвадор" },
  { alpha2: "SX", name: "Сен-мартен (нидерландская часть)" },
  { alpha2: "SY", name: "Сирийская арабская республика" },
  { alpha2: "SZ", name: "Эсватини" },
  { alpha2: "TC", name: "Острова теркс и кайкос" },
  { alpha2: "TD", name: "Чад" },
  { alpha2: "TF", name: "Французские южные территории" },
  { alpha2: "TG", name: "Того" },
  { alpha2: "TH", name: "Таиланд" },
  { alpha2: "TJ", name: "Таджикистан" },
  { alpha2: "TK", name: "Токелау" },
  { alpha2: "TL", name: "Тимор-лесте" },
  { alpha2: "TM", name: "Туркменистан" },
  { alpha2: "TN", name: "Тунис" },
  { alpha2: "TO", name: "Тонга" },
  { alpha2: "TR", name: "Турция" },
  { alpha2: "TT", name: "Тринидад и тобаго" },
  { alpha2: "TV", name: "Тувалу" },
  { alpha2: "TW", name: "Тайвань (китай)" },
  { alpha2: "TZ", name: "Танзания, объединенная республика" },
  { alpha2: "UA", name: "Украина" },
  { alpha2: "UG", name: "Уганда" },
  { alpha2: "UM", name: "Малые тихоокеан.отдален.ост-ва с.ш." },
  { alpha2: "US", name: "Соединенные штаты" },
  { alpha2: "UY", name: "Уругвай" },
  { alpha2: "UZ", name: "Узбекистан" },
  { alpha2: "VA", name: "Папский престол (гос.-город ватикан)" },
  { alpha2: "VC", name: "Сент-винсент и гренадины" },
  { alpha2: "VE", name: "Венесуэла, боливарианская республика" },
  { alpha2: "VG", name: "Виргинские острова (британские)" },
  { alpha2: "VI", name: "Виргинские острова (сша)" },
  { alpha2: "VN", name: "Вьетнам" },
  { alpha2: "VU", name: "Вануату" },
  { alpha2: "WF", name: "Уоллис и футуна" },
  { alpha2: "WS", name: "Самоа" },
  { alpha2: "YE", name: "Йемен" },
  { alpha2: "YT", name: "Майотта" },
  { alpha2: "ZA", name: "Южная африка" },
  { alpha2: "ZM", name: "Замбия" },
  { alpha2: "ZW", name: "Зимбабве" },
]

export const EAEU_ALPHA2 = new Set(["RU", "BY", "KZ", "AM", "KG"])
